### ISSUE TITLE
Feature request: Automatically pathexpand ssh_public_key_path

### ISSUE THREAD

**Issue by looneym** [cloudposse/terraform-aws-key-pair#9] opened 2018-03-13 20:43 UTC
Currently I have to do this:

 ```
"ssh_public_key_path" = "${pathexpand(~/.ssh)}"
```

It would be nice if the module called pathexpand on this variable automatically. I think most people who put `~` in this field want it to be interpolated as `$HOME`

**Comment by looneym** [comment] 2018-03-13 20:47
This actuall doesn't work. I can't seem to find a way to get the path to expand. Specifying a full path is not ideal

**Comment by osterman** [comment] 2018-03-13 23:15
Looks like a simple syntax error:

try:
```
ssh_public_key_path = "${pathexpand("~/.ssh")}"
```

The problem is that `~/.ssh` is invalid.

**Comment by osterman** [comment] 2018-03-13 23:15
If you submit a PR, I'll accept it. =)

**Comment by aknysh** [comment] 2018-04-27 19:57
@looneym 
thanks a lot for testing!
we think we should not include that into the module for a few reasons:

1. `"ssh_public_key_path" = "${pathexpand(~/.ssh)}"` is how you call it from a top-level module. It should not be in this module because for many use-cases (e.g. using it from TravisCI or CodeFresh) `pathexpand` is not needed

2. If `pathexpand` is included in the module, it will create a plan diff between two different hosts, unless the filepaths are the same (https://www.terraform.io/docs/configuration/interpolation.html#pathexpand-string-)
 
we'll close the issue for now.
thanks again!

**Closed by aknysh** 2018-04-27 19:57 UTC
Labels: feature request
